# Generated by Django 5.2.1 on 2025-05-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='age_group',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='patient_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='electromyography',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hasID',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='oxygen_saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='triage_code',
            field=models.CharField(blank=True, choices=[('white', 'White - Not Urgent'), ('green', 'Green - Minor Urgent'), ('deepskyblue', 'Light Blue - Deferrable Urgency'), ('orange', 'Orange - Urgent'), ('red', 'Red - Major Urgent')], max_length=15, null=True),
        ),
    ]
