# Generated by Django 5.2.1 on 2025-05-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0003_remove_ambulance_staff_ambulance_staff'),
        ('patients', '0004_alter_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_ambulance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='ambulance.ambulance'),
        ),
    ]
