# Generated by Django 5.2 on 2025-04-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('symptoms', models.JSONField(blank=True, default=list, null=True)),
                ('triage_code', models.CharField(blank=True, choices=[('white', 'White - No triage'), ('green', 'Green - Minor'), ('orange', 'Orange - Moderate'), ('red', 'Red - Major')], max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('complexion', models.CharField(blank=True, max_length=20, null=True)),
                ('hair', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
