version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: er_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ER
      POSTGRES_PASSWORD: ER
      POSTGRES_DB: er_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./emer.sql:/docker-entrypoint-initdb.d/emer.sql  # optional schema
    networks:
      - ernet

  pgadmin:
    image: dpage/pgadmin4
    container_name: er_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - ernet

volumes:
  pgdata:

networks:
  ernet:
