# Generated by Django 5.2.1 on 2025-05-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='staff',
        ),
    ]
