# Generated by Django 5.2.1 on 2025-05-27 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_ambulance_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='staff',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_ambulances', to=settings.AUTH_USER_MODEL),
        ),
    ]
