# Generated by Django 5.2.1 on 2025-05-27 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0003_remove_ambulance_staff_ambulance_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='staff',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='staff',
            field=models.ManyToManyField(related_name='ambulances', to=settings.AUTH_USER_MODEL),
        ),
    ]
