# Generated by Django 5.2.1 on 2025-05-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='age_group',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='complexion',
            new_name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hair',
        ),
        migrations.AlterField(
            model_name='patient',
            name='triage_code',
            field=models.CharField(blank=True, choices=[('white', 'White - Not Urgent'), ('green', 'Green - Minor'), ('orange', 'Orange - Moderate'), ('red', 'Red - Major')], max_length=10, null=True),
        ),
    ]
